# Netlify build configuration
[build]
  # Build command (no build process needed for static site)
  command = "echo 'Static site - no build required'"
  
  # Directory to publish
  publish = "."
  
  # Functions directory (not used in this project)
  # functions = "netlify/functions"

[build.environment]
  # Node version (for any future build processes)
  NODE_VERSION = "18"

# Headers for better caching and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # Cache control for HTML files (short cache for updates)
    Cache-Control = "public, max-age=300, s-maxage=300"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "font/woff2"

# Redirects and rewrites
[[redirects]]
  from = "/api/dollar/*"
  to = "https://api.bluelytics.com.ar/v2/:splat"
  status = 200
  force = false
  
[[redirects]]
  from = "/api/dollar-backup/*"
  to = "https://dolarapi.com/v1/:splat"
  status = 200
  force = false

# SPA fallback - redirect all non-asset requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.9
    pwa = 0.8

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://portal-noticias-argentina.netlify.app"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing"
    ]