# Netlify build configuration - Simple and working version
[build]
  publish = "."

# Basic redirects only
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"